security:
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/course/info, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/course/search, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/course/new, roles: [ROLE_ADMIN, ROLE_TEACHER] }
        - { path: ^/course, roles: [ROLE_TEACHER, ROLE_USER] }
        - { path: ^/profile, roles: [ROLE_TEACHER, ROLE_USER] }
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                provider: my_provider
                username_parameter: "login_form[username]"
                password_parameter: "login_form[password]"
                default_target_path: index
            logout:
                path: logout
                target: public
    providers:
        my_provider:
            entity:
                class: App\Entity\User
                property: username
    role_hierarchy:
            ROLE_ADMIN: ROLE_TEACHER


